### ISSUE TITLE
gnuradio-runtime.pc missing boost dependencies

### ISSUE THREAD

**Issue by ast** [gnuradio/gnuradio#2268]
Depends on boost but they are not in ```Libs``` so if you build a program that uses the C++ API you need to list boost as a dependency, using pkg-config is not enough. 

Adding ```-llibboost_system```should be enough.

```
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: gnuradio-runtime
Description: GNU Radio core runtime infrastructure
Requires:
Version: 3.7.13.4
Libs: -L${libdir} -lgnuradio-runtime -lgnuradio-pmt -llog4cpp
Cflags: -I${includedir}
```

**Comment by marcusmueller** [comment]
It feels like we should be able to solve this rather elegantly with the modern CMake that Mait and @noc0lour encouraged, but I don't know how.

**Comment by michaelld** [comment]
At least on OSX, the DYLD needs -all- library dependencies ... in modern CMake notation: Volk::volk, Boost::date_time, Boost::program_options, Boost::filesystem, Boost::system, Boost::regex, Boost::thread, Boost::unit_test_framework, Boost::chrono, Boost::atomic.

Modern CMake targets should be usable via some PROPERTY retrieval & substitution via CMake ... might have to create temporary variables for the substitution; not sure if CMake allows target PROPERTY substitutions directly.

I do agree that this should be fixed, even if the vast majority of projects needing GR use CMake & thus don't use PKGCONFIG or this file.

**Comment by bhilburn** [comment]
We suspect there are changes already made, here, tagging @noc0lour to look at this issue further.

**Comment by marcusmueller** [comment]
ping @noc0lour

**Comment by noc0lour** [comment]
@ast What's your usecase for using the pkg-config ? With the new cmake in place there is little to no need for having pkg-config out there.

**Comment by noc0lour** [comment]
For generating the right pkgconfig this is probably a good starting point
https://stackoverflow.com/questions/44292462/how-to-auto-generate-pkgconfig-files-from-cmake-targets

**Comment by ast** [comment]
@noc0lour use case is building an application using the C++ API.

**Comment by noc0lour** [comment]
So this still needs to be done for the packageconfig files, manually updating packagconfig files is not really manageable.

**Comment by NeuroForLunch** [comment]
I assume this issue has been resolved?

**Comment by marcusmueller** [comment]
Not really solved, we seem to be missing spdlog dependencies now
